services:
  - type: web
    name: multilang-site
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    start_cmd: gunicorn multilang_site.wsgi:application --bind 0.0.0.0:$PORT
    health_check_path: /
    env_vars:
      PYTHONUNBUFFERED: 'true'
    env:
      - key: PORT
        value: '8000'
      - key: ALLOWED_HOSTS
        value: '*'
    envVars:
      - key: PORT
        value: '8000'
      - key: SECRET_KEY
        value: <django-insecure-!y6y6x5d8c0jdk+qcti9-p9&9^hsye9qb+a3o$ikycsy6@j!s6>
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: OPENAI_API_KEY
        value: <sk-proj-FRnIOzqFa9vLnlIU0c5RT3BlbkFJQTCIW1nMlQTtMGs7gOJ5>
